apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hidq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hidq
    app.kubernetes.io/part-of: tkrw-pr714-0075-0002-app
  name: devfile-sample-hidq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hidq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hidq
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0002-tenant/tkrw-pr714-0075-0002-app/devfile-sample-hidq@sha256:c89c12154facdfc062c319716e629b88fdb6fa8b58e53e8ff6ad90ab444d7497
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
